# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2bb12a44c83663a69b3fd077226c75ab"
name = "Rev signal: Profit analytics"
application_url = "https://dev-api.revsignallab.com/api/store"
embedded = false
handle = "dev-rev-signal"

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_customers"

[auth]
redirect_urls = [
  "https://dev-api.revsignallab.com/api/store/auth",
  "https://dev-api.revsignallab.com/api/store/auth/user"
]

[pos]
embedded = false
